LINEAR_KP: 0.5
LINEAR_KD: 2
LINEAR_KI: 0
LINEAR_MAX_I: 50

MAX_DUTY: 255
MIN_DUTY: 0

LOOP_CONTROL_MS: 40
TELEMETRY_SIZE_BYTES: 30

# Slew rate of the motors (limit changes in PWM)
MOT_SLEWRATE: 20

# Maximum change acceleration/decceleartion in one iteration (manual commands)
FF_GAIN: 0.2
FF_MAX_ACC: 25000

# mptt vars
MPTT_KP: 1
MPTT_KD: 0
MPTT_KI: 0
MPTT_MAX_I: 0

# Serial configuraiton
SERIAL_PORT: /dev/ttyUSB0
SERIAL_RATE: 115200
RADIO_IDLE_TIMEOUT: 5000

# benchmark information
BENCHY_MIN_DUTY: 0
BENCHY_MAX_DUTY: 255
BENCHY_STEP: 20
BENCHY_MS_STEEP: 1000
BENCHY_MS_PLATEAU: 2000
BENCHY_ITERATIONS: 1