LINEAR_KP: 0.5
LINEAR_KD: 2
LINEAR_KI: 0
LINEAR_MAX_I: 50

MAX_DUTY: 255
MIN_DUTY: 0

LOOP_CONTROL_MS: 40
TELEMETRY_SIZE_BYTES: 30

MOT_SLEWRATE: 20

# Serial configuraiton
SERIAL_PORT: /dev/ttyUSB0
SERIAL_RATE: 115200
RADIO_IDLE_TIMEOUT: 5000

# benchmark information
BENCHY_MIN_DUTY: 0
BENCHY_MAX_DUTY: 255
BENCHY_STEP: 20
BENCHY_MS_STEEP: 1000
BENCHY_MS_PLATEAU: 2000
BENCHY_ITERATIONS: 1